logdir: null
accelerator: gpu
devices: 1
seed: 23
expname: Cmamba
config: nlinear_linattn_v1
logger_type: tb
num_workers: 4
batch_size: 32
save_checkpoints: true
use_volume: true
resume_from_checkpoint: null
max_epochs: 1500
data_config: binance_full
model: NLinearLinAttn_v1
name: nlinear_linattn
hyperparams:
  optimizer: adam
  lr: 0.001
  lr_step_size: 100
  lr_gamma: 0.75
  weight_decay: 0.0001
