logdir: null
accelerator: gpu
devices: 1
seed: 23
expname: Cmamba
config: gru_v
logger_type: tb
num_workers: 4
batch_size: 32
save_checkpoints: true
use_volume: true
resume_from_checkpoint: null
max_epochs: 1000
data_config: binance_full
model: GRU_v
name: gru
hyperparams:
  optimizer: adam
  lr: 0.001
  lr_step_size: 100
  lr_gamma: 0.5
  weight_decay: 0.0001
